use std::fs;
use std::path::Path;

fn main() {
    // Try multiple possible paths to locate the database migrations
    let paths = vec![
        "../../../Documents/partisipasi-sekolah/database/migrations",
        "/Users/ardianryan/Documents/partisipasi-sekolah/database/migrations",
        "../../partisipasi-sekolah/database/migrations",
    ];

    let mut source_dir_opt = None;
    for p in paths {
        let path = Path::new(p);
        if path.exists() && path.is_dir() {
            source_dir_opt = Some(path);
            break;
        }
    }

    let target_migration_dir = Path::new("./migrations_bundle");

    if let Some(source_migration_dir) = source_dir_opt {
        println!("cargo:warning=Copying database migrations from {:?}", source_migration_dir);
        fs::create_dir_all(target_migration_dir).unwrap();
        if let Ok(entries) = fs::read_dir(source_migration_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file() && path.extension().map_or(false, |ext| ext == "sql") {
                    let dest = target_migration_dir.join(path.file_name().unwrap());
                    fs::copy(&path, &dest).unwrap();
                }
            }
        }
    } else {
        println!("cargo:warning=Warning: Database migrations directory not found. Using existing migrations if any.");
    }

    // Now, generate src/migrations.rs containing compile-time references to all SQL files
    let mut sql_files = Vec::new();
    if target_migration_dir.exists() {
        if let Ok(entries) = fs::read_dir(target_migration_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file() && path.extension().map_or(false, |ext| ext == "sql") {
                    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                        sql_files.push(name.to_string());
                    }
                }
            }
        }
    }

    // Sort files to guarantee order
    sql_files.sort();

    let mut code = String::new();
    code.push_str("// This file is auto-generated by build.rs. Do not edit manually.\n\n");
    code.push_str("pub static MIGRATIONS: &[(&str, &str)] = &[\n");
    for file in &sql_files {
        code.push_str(&format!(
            "    (\"{}\", include_str!(\"../migrations_bundle/{}\")),\n",
            file, file
        ));
    }
    code.push_str("];\n");

    fs::write("src/migrations.rs", code).unwrap();
    println!("cargo:warning=Generated src/migrations.rs with {} migration files.", sql_files.len());

    tauri_build::build();
}
