-- Students table
CREATE TABLE IF NOT EXISTS `students` (
    `id` VARCHAR(36) NOT NULL,
    `sso_member_id` VARCHAR(36) NOT NULL,
    `user_id` VARCHAR(36) DEFAULT NULL,
    `nama` VARCHAR(100) NOT NULL,
    `nis` VARCHAR(30) DEFAULT NULL,
    `nisn` VARCHAR(20) DEFAULT NULL,
    `jenis_kelamin` ENUM('L','P') DEFAULT NULL,
    `kelas` VARCHAR(50) DEFAULT NULL,
    `classroom_id` VARCHAR(36) DEFAULT NULL,
    `academic_year_id` VARCHAR(36) DEFAULT NULL,
    `google_email` VARCHAR(100) DEFAULT NULL,
    `google_avatar` VARCHAR(500) DEFAULT NULL,
    `no_telepon` VARCHAR(20) DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `ayah_nama` VARCHAR(100) DEFAULT NULL,
    `ibu_nama` VARCHAR(100) DEFAULT NULL,
    `wali_nama` VARCHAR(100) DEFAULT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_students_sso_member_id` (`sso_member_id`),
    KEY `idx_students_user_id` (`user_id`),
    KEY `idx_students_classroom_id` (`classroom_id`),
    KEY `idx_students_academic_year_id` (`academic_year_id`),
    KEY `idx_students_nis` (`nis`),
    KEY `idx_students_nisn` (`nisn`),
    KEY `idx_students_nama` (`nama`),
    CONSTRAINT `fk_students_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_students_classroom` FOREIGN KEY (`classroom_id`) REFERENCES `classrooms`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_students_academic_year` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
