CREATE TABLE IF NOT EXISTS `online_payment_orders` (
    `id` VARCHAR(36) NOT NULL,
    `order_id` VARCHAR(50) NOT NULL,
    `student_id` VARCHAR(36) NOT NULL,
    `user_id` VARCHAR(36) NOT NULL,
    `academic_year_id` VARCHAR(36) NOT NULL,
    `payment_id` VARCHAR(36) DEFAULT NULL,
    `total_amount` DECIMAL(15,2) NOT NULL DEFAULT 0,
    `snap_token` VARCHAR(200) DEFAULT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'pending',
    `payment_type` VARCHAR(50) DEFAULT NULL,
    `transaction_id` VARCHAR(100) DEFAULT NULL,
    `pdf_url` TEXT DEFAULT NULL,
    `raw` TEXT DEFAULT NULL,
    `is_applied` TINYINT(1) NOT NULL DEFAULT 0,
    `invalidated_at` DATETIME DEFAULT NULL,
    `invalidated_by` VARCHAR(36) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_op_order_id` (`order_id`),
    KEY `idx_op_student` (`student_id`),
    KEY `idx_op_user` (`user_id`),
    KEY `idx_op_academic_year` (`academic_year_id`),
    KEY `idx_op_payment` (`payment_id`),
    KEY `idx_op_status` (`status`),
    KEY `idx_op_created_at` (`created_at`),
    KEY `idx_op_invalidated_by` (`invalidated_by`),
    CONSTRAINT `fk_op_student` FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_op_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_op_academic_year` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_op_payment` FOREIGN KEY (`payment_id`) REFERENCES `payments`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_op_invalidated_by` FOREIGN KEY (`invalidated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
